[package]
name = "init"
version = "0.1.0"
edition = "2021"
authors = ["Atom OS Contributors"]
description = "Init process (PID 1) - orchestrates boot sequence"

[dependencies]
atom_syscall = { path = "../../libs/syscall" }
libipc = { path = "../../libs/libipc" }

[[bin]]
name = "init"
path = "src/main.rs"
