[package]
name = "libgui"
license = "Apache-2.0"
publish = false
version = "0.1.0"
edition = "2021"
authors = ["Atom OS Contributors"]
description = "GUI library for Atom OS userspace applications"

[dependencies]
atom_syscall = { path = "../syscall" }
atom_theme   = { path = "../atom_theme" }
libipc       = { path = "../libipc" }

[lib]
crate-type = ["rlib"]
