[package]
name = "timesync"
version = "0.1.0"
edition = "2021"

[dependencies]
atom_syscall = { path = "../../libs/syscall" }
libipc = { path = "../../libs/libipc" }
libnet = { path = "../../libs/libnet" }

[[bin]]
name = "timesync"
path = "src/main.rs"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
