[workspace]
members = [
    "shared/abi",
    "kernel",
    "userspace/libs/syscall",
    "userspace/libs/libipc",
    "userspace/libs/libgui",
    "userspace/libs/atom_theme",
    "userspace/libs/atom_ui",
    "userspace/libs/libimage",
    "userspace/libs/libring",
]
# Os drivers userspace serao compilados separadamente como binarios ATXF
# quando o loader de executaveis estiver pronto.
# Por enquanto, o kernel usa um shell embutido (shell.rs).
exclude = [
    "userspace/apps/fileman",
    "userspace/apps/fs_test",
    "userspace/system_apps/keyboard",
    "userspace/system_apps/mouse",
    "userspace/system_apps/display",
    "userspace/system_apps/terminal",
    "userspace/system_apps/ui_shell",
    "userspace/system_apps/demo_rects",
    "userspace/system_apps/demo_text",
    "userspace/services/init",
    "userspace/services/namesvc",
    "userspace/services/service_manager",
    "userspace/services/fsd",
    "userspace/services/app_launcher",
    "userspace/apps/hello_atxf",
    "userspace/services/nic_driver",
    "userspace/services/netd",
]
resolver = "2"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = "z"
lto = true
codegen-units = 1