// kernel/build.rs
//
// Single source of truth for IRQ vector assignments.
//
// Changing a vector number here propagates automatically to both consumers:
//   - Rust  : kernel/target/.../out/vectors.rs  (included by interrupts/mod.rs)
//   - NASM  : kernel/src/interrupts/vectors.inc  (included by handlers.asm)
//
// Do NOT edit vectors.inc or the generated vectors.rs by hand; edit this
// file instead and rebuild.

use std::{env, fs, path::PathBuf};

fn main() {
    // -----------------------------------------------------------------------
    // Vector table — edit here to change assignments.
    // Values must fit in a u8 (0–255).
    // -----------------------------------------------------------------------
    let vectors: &[(&str, u8)] = &[
        ("TIMER_INTERRUPT_VECTOR",    32),
        ("KEYBOARD_INTERRUPT_VECTOR", 33),
        ("MOUSE_INTERRUPT_VECTOR",    44),
        ("USER_TRAP_INTERRUPT_VECTOR", 0x68),
    ];

    // -----------------------------------------------------------------------
    // Rust side — write OUT_DIR/vectors.rs, included by interrupts/mod.rs.
    // -----------------------------------------------------------------------
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let mut rs = String::from("// Auto-generated by kernel/build.rs — do not edit manually.\n");
    for (name, val) in vectors {
        rs.push_str(&format!("pub const {}: u8 = {};\n", name, val));
    }
    fs::write(out_dir.join("vectors.rs"), &rs).unwrap();

    // -----------------------------------------------------------------------
    // NASM side — write kernel/src/interrupts/vectors.inc, included by
    // handlers.asm via `%include "vectors.inc"`.  Written into the same
    // directory as handlers.asm so NASM can find it without an extra -I flag.
    // -----------------------------------------------------------------------
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let inc_path = manifest_dir
        .join("src")
        .join("interrupts")
        .join("vectors.inc");
    let mut inc =
        String::from("; Auto-generated by kernel/build.rs — do not edit manually.\n");
    for (name, val) in vectors {
        inc.push_str(&format!("%define {:<28} {}\n", name, val));
    }
    fs::write(&inc_path, &inc).unwrap();

    println!("cargo:rerun-if-changed=build.rs");
}
