; kernel/src/interrupts/handlers.asm
;
; Interrupt and exception handler stubs for x86_64.
;
; IRQ vector numbers come from vectors.inc, generated by kernel/build.rs (the
; single source of truth). Edit build.rs to change vectors; never edit
; vectors.inc directly.
;
; Each stub builds a uniform `InterruptFrame` on the stack:
;     [vector][error_code]  (pushed here)
;     r15 .. rax            (pushed by PUSH_ALL)
; and passes a pointer to it as the first argument. The matching Rust layout is
; `handlers::InterruptFrame` (compile-time-checked there to be 176 bytes).
;
; Calling convention: the Rust handlers take their argument in RCX with 32 bytes
; of shadow space (MS x64). CALL_RUST_HANDLER enforces both that and 16-byte
; stack alignment at the call site.

%include "vectors.inc"

[BITS 64]
section .text

; External Rust handlers
extern rust_exception_handler
extern rust_unexpected_interrupt_handler
extern rust_timer_interrupt_handler
extern rust_keyboard_interrupt_handler
extern rust_mouse_interrupt_handler
extern rust_reschedule_interrupt_handler
extern rust_user_trap_interrupt_handler

; ---------------------------------------------------------------------------
; Register save / restore
; ---------------------------------------------------------------------------

%macro PUSH_ALL 0
    push rax
    push rbx
    push rcx
    push rdx
    push rsi
    push rdi
    push rbp
    push r8
    push r9
    push r10
    push r11
    push r12
    push r13
    push r14
    push r15
%endmacro

%macro POP_ALL 0
    pop r15
    pop r14
    pop r13
    pop r12
    pop r11
    pop r10
    pop r9
    pop r8
    pop rbp
    pop rdi
    pop rsi
    pop rdx
    pop rcx
    pop rbx
    pop rax
    add rsp, 16                 ; drop pushed vector + error_code
%endmacro

; ---------------------------------------------------------------------------
; MS x64 ABI helper: 16-byte alignment + 32-byte shadow space.
; RBP is used as scratch to save/restore RSP; PUSH_ALL already saved the
; caller's RBP and POP_ALL will restore it.
; ---------------------------------------------------------------------------
%macro CALL_RUST_HANDLER 1
    mov rbp, rsp
    sub rsp, 32
    and rsp, -16
    call %1
    mov rsp, rbp
%endmacro

; ---------------------------------------------------------------------------
; GS management. After PUSH_ALL the pushed CS sits at [rsp + 144]; its low two
; bits are the RPL. If we came from CPL=3 we swap to the kernel GS base on
; entry and swap back on exit. Macro-local labels (%%) keep multiple uses in
; the same function from colliding.
; ---------------------------------------------------------------------------
%macro INTERRUPT_ENTRY 0
    test qword [rsp + 144], 0x3
    jz %%kernel_entry
    swapgs
%%kernel_entry:
%endmacro

%macro INTERRUPT_EXIT 0
    test qword [rsp + 144], 0x3
    jz %%kernel_exit
    swapgs
%%kernel_exit:
%endmacro

; ---------------------------------------------------------------------------
; Catch-all stub table (one entry per vector). idt.rs reads
; `unexpected_interrupt_table` to pre-fill every IDT slot.
; ---------------------------------------------------------------------------
global unexpected_interrupt_table

unexpected_interrupt_table:
%assign vec 0
%rep 256
    dq unexpected_interrupt_handler_%[vec]
%assign vec vec + 1
%endrep

%macro UNEXPECTED_INTERRUPT_HANDLER 1
global unexpected_interrupt_handler_%1
unexpected_interrupt_handler_%1:
    push qword 0                ; dummy error code
    push qword %1               ; vector
    jmp unexpected_common
%endmacro

%assign vec 0
%rep 256
UNEXPECTED_INTERRUPT_HANDLER vec
%assign vec vec + 1
%endrep

unexpected_common:
    PUSH_ALL
    INTERRUPT_ENTRY
    mov rcx, rsp                ; arg0 = InterruptFrame*
    CALL_RUST_HANDLER rust_unexpected_interrupt_handler
    INTERRUPT_EXIT
    POP_ALL
    iretq

; ---------------------------------------------------------------------------
; Hardware IRQ stubs. One macro generates all of them; the global symbol names
; (irq_handler_32, ...) are referenced by idt.rs and must stay stable.
; ---------------------------------------------------------------------------
%macro IRQ_STUB 3                ; %1=symbol  %2=vector const  %3=rust handler
global %1
%1:
    push qword 0                ; dummy error code
    push qword %2               ; vector
    PUSH_ALL
    INTERRUPT_ENTRY
    mov rcx, rsp
    CALL_RUST_HANDLER %3
    INTERRUPT_EXIT
    POP_ALL
    iretq
%endmacro

IRQ_STUB irq_handler_32,  TIMER_INTERRUPT_VECTOR,      rust_timer_interrupt_handler
IRQ_STUB irq_handler_33,  KEYBOARD_INTERRUPT_VECTOR,   rust_keyboard_interrupt_handler
IRQ_STUB irq_handler_44,  MOUSE_INTERRUPT_VECTOR,      rust_mouse_interrupt_handler
IRQ_STUB irq_handler_45,  RESCHEDULE_INTERRUPT_VECTOR, rust_reschedule_interrupt_handler
IRQ_STUB irq_handler_104, USER_TRAP_INTERRUPT_VECTOR,  rust_user_trap_interrupt_handler

; ---------------------------------------------------------------------------
; Exception stubs. Vectors that push their own hardware error code use
; EXCEPTION_HANDLER_ERR; the rest push a dummy 0 to keep the frame uniform.
; ---------------------------------------------------------------------------
%macro EXCEPTION_HANDLER_NO_ERR 1
global exception_handler_%1
exception_handler_%1:
    push qword 0                ; dummy error code
    push qword %1               ; vector
    jmp exception_common
%endmacro

%macro EXCEPTION_HANDLER_ERR 1
global exception_handler_%1
exception_handler_%1:
    push qword %1               ; vector (CPU already pushed the error code)
    jmp exception_common
%endmacro

EXCEPTION_HANDLER_NO_ERR 0     ; #DE Divide Error
EXCEPTION_HANDLER_NO_ERR 1     ; #DB Debug
EXCEPTION_HANDLER_NO_ERR 2     ; NMI
EXCEPTION_HANDLER_NO_ERR 3     ; #BP Breakpoint
EXCEPTION_HANDLER_NO_ERR 4     ; #OF Overflow
EXCEPTION_HANDLER_NO_ERR 5     ; #BR Bound Range Exceeded
EXCEPTION_HANDLER_NO_ERR 6     ; #UD Invalid Opcode
EXCEPTION_HANDLER_NO_ERR 7     ; #NM Device Not Available
EXCEPTION_HANDLER_ERR    8     ; #DF Double Fault
EXCEPTION_HANDLER_NO_ERR 9     ; (reserved / legacy coprocessor segment overrun)
EXCEPTION_HANDLER_ERR    10    ; #TS Invalid TSS
EXCEPTION_HANDLER_ERR    11    ; #NP Segment Not Present
EXCEPTION_HANDLER_ERR    12    ; #SS Stack-Segment Fault
EXCEPTION_HANDLER_ERR    13    ; #GP General Protection
EXCEPTION_HANDLER_ERR    14    ; #PF Page Fault
EXCEPTION_HANDLER_NO_ERR 16    ; #MF x87 FPU
EXCEPTION_HANDLER_ERR    17    ; #AC Alignment Check
EXCEPTION_HANDLER_NO_ERR 18    ; #MC Machine Check
EXCEPTION_HANDLER_NO_ERR 19    ; #XM SIMD FP
EXCEPTION_HANDLER_NO_ERR 20    ; #VE Virtualization
EXCEPTION_HANDLER_ERR    21    ; #CP Control Protection

exception_common:
    PUSH_ALL
    INTERRUPT_ENTRY
    mov rcx, rsp                ; arg0 = InterruptFrame*
    CALL_RUST_HANDLER rust_exception_handler
    INTERRUPT_EXIT
    POP_ALL
    iretq