; kernel/src/interrupts/handlers.asm
;
; Interrupt and exception handler stubs for x86_64
;
; IRQ vector assignments come from vectors.inc, which is generated by
; kernel/build.rs (the single source of truth).  Edit build.rs to change
; vector numbers; do not edit vectors.inc directly.
%include "vectors.inc"

[BITS 64]

section .text

; External Rust handler functions
extern rust_exception_handler
extern rust_unexpected_interrupt_handler
extern rust_timer_interrupt_handler
extern rust_keyboard_interrupt_handler
extern rust_mouse_interrupt_handler
extern rust_reschedule_interrupt_handler
extern rust_user_trap_interrupt_handler

%macro PUSH_ALL 0
    push rax
    push rbx
    push rcx
    push rdx
    push rsi
    push rdi
    push rbp
    push r8
    push r9
    push r10
    push r11
    push r12
    push r13
    push r14
    push r15
%endmacro

%macro POP_ALL 0
    pop r15
    pop r14
    pop r13
    pop r12
    pop r11
    pop r10
    pop r9
    pop r8
    pop rbp
    pop rdi
    pop rsi
    pop rdx
    pop rcx
    pop rbx
    pop rax
    add rsp, 16                    ; drop vector + error_code
%endmacro

; ---------------------------------------------------------------------------
; ABI Compliance Helper Macro
; ---------------------------------------------------------------------------

; CALL_RUST_HANDLER <handler_name>
; Ensures MS x64 ABI compliance:
; 1. Stack is 16-byte aligned before the call.
; 2. 32 bytes of shadow space (home space) are reserved.
; Uses RBP as a scratch register to save/restore RSP. This is safe because
; PUSH_ALL has already saved the original RBP on the stack, and POP_ALL
; will restore it later.
%macro CALL_RUST_HANDLER 1
    mov rbp, rsp           ; Save current stack pointer
    sub rsp, 32            ; Allocate shadow space
    and rsp, -16           ; Align to 16-byte boundary
    call %1                ; Call the actual handler
    mov rsp, rbp           ; Restore original stack pointer
%endmacro

; ---------------------------------------------------------------------------
; Catch-all interrupt stubs
; ---------------------------------------------------------------------------

global unexpected_interrupt_table

unexpected_interrupt_table:
%assign vec 0
%rep 256
    dq unexpected_interrupt_handler_%[vec]
%assign vec vec + 1
%endrep

; ---------------------------------------------------------------------------
; Unexpected interrupt handlers (no error code)
; ---------------------------------------------------------------------------

%macro UNEXPECTED_INTERRUPT_HANDLER 1
global unexpected_interrupt_handler_%1
unexpected_interrupt_handler_%1:
    push qword 0
    push qword %1
    jmp unexpected_common
%endmacro

%assign vec 0
%rep 256
UNEXPECTED_INTERRUPT_HANDLER vec
%assign vec vec + 1
%endrep

; ---------------------------------------------------------------------------
; Common handler for unexpected interrupts (vectors without a dedicated stub)
; ---------------------------------------------------------------------------
unexpected_common:
    PUSH_ALL
    mov rcx, rsp           ; arg0 = InterruptFrame*
    CALL_RUST_HANDLER rust_unexpected_interrupt_handler
    POP_ALL
    iretq

; ---------------------------------------------------------------------------
; Exception handler macros
; ---------------------------------------------------------------------------

%macro EXCEPTION_HANDLER_NO_ERR 1
global exception_handler_%1
exception_handler_%1:
    push qword 0          ; dummy error code
    push qword %1         ; vector
    jmp exception_common
%endmacro

%macro EXCEPTION_HANDLER_ERR 1
global exception_handler_%1
exception_handler_%1:
    push qword %1
    jmp exception_common
%endmacro

; ---------------------------------------------------------------------------
; IRQ Handlers
; ---------------------------------------------------------------------------

global irq_handler_32
irq_handler_32:
    push qword 0
    push qword TIMER_INTERRUPT_VECTOR
    PUSH_ALL
    mov rcx, rsp
    CALL_RUST_HANDLER rust_timer_interrupt_handler
    POP_ALL
    iretq

global irq_handler_104
irq_handler_104:
    push qword 0
    push qword USER_TRAP_INTERRUPT_VECTOR
    PUSH_ALL
    mov rcx, rsp
    CALL_RUST_HANDLER rust_user_trap_interrupt_handler
    POP_ALL
    iretq

global irq_handler_33
irq_handler_33:
    push qword 0
    push qword KEYBOARD_INTERRUPT_VECTOR
    PUSH_ALL
    mov rcx, rsp
    CALL_RUST_HANDLER rust_keyboard_interrupt_handler
    POP_ALL
    iretq

global irq_handler_44
irq_handler_44:
    push qword 0
    push qword MOUSE_INTERRUPT_VECTOR
    PUSH_ALL
    mov rcx, rsp
    CALL_RUST_HANDLER rust_mouse_interrupt_handler
    POP_ALL
    iretq

global irq_handler_45
irq_handler_45:
    push qword 0
    push qword RESCHEDULE_INTERRUPT_VECTOR
    PUSH_ALL
    mov rcx, rsp
    CALL_RUST_HANDLER rust_reschedule_interrupt_handler
    POP_ALL
    iretq

; ---------------------------------------------------------------------------
; Exception handlers (0–31)
; ---------------------------------------------------------------------------

EXCEPTION_HANDLER_NO_ERR 0    ; #DE Divide Error
EXCEPTION_HANDLER_NO_ERR 1    ; #DB Debug
EXCEPTION_HANDLER_NO_ERR 2    ; NMI
EXCEPTION_HANDLER_NO_ERR 3    ; #BP Breakpoint
EXCEPTION_HANDLER_NO_ERR 4    ; #OF Overflow
EXCEPTION_HANDLER_NO_ERR 5    ; #BR Bound Range Exceeded
EXCEPTION_HANDLER_NO_ERR 6    ; #UD Invalid Opcode
EXCEPTION_HANDLER_NO_ERR 7    ; #NM Device Not Available
EXCEPTION_HANDLER_ERR    8    ; #DF Double Fault
EXCEPTION_HANDLER_NO_ERR 9
EXCEPTION_HANDLER_ERR    10   ; #TS Invalid TSS
EXCEPTION_HANDLER_ERR    11   ; #NP Segment Not Present
EXCEPTION_HANDLER_ERR    12   ; #SS Stack-Segment Fault
EXCEPTION_HANDLER_ERR    13   ; #GP General Protection
EXCEPTION_HANDLER_ERR    14   ; #PF Page Fault
EXCEPTION_HANDLER_NO_ERR 16   ; #MF x87 FPU
EXCEPTION_HANDLER_ERR    17   ; #AC Alignment Check
EXCEPTION_HANDLER_NO_ERR 18   ; #MC Machine Check
EXCEPTION_HANDLER_NO_ERR 19   ; #XM SIMD FP
EXCEPTION_HANDLER_NO_ERR 20   ; #VE Virtualization
EXCEPTION_HANDLER_ERR    21   ; #CP Control Protection

; ---------------------------------------------------------------------------
; Common exception handler
; ---------------------------------------------------------------------------

exception_common:
    PUSH_ALL
    mov rcx, rsp           ; arg0 = InterruptFrame*
    CALL_RUST_HANDLER rust_exception_handler
    POP_ALL
    iretq
