// kernel/src/interrupts/mod.rs
// Interrupt subsystem orchestration for x86_64.

#![allow(dead_code)]
//
// This module is intentionally small and policy-oriented.  The low-level work
// is split into the three architecture modules below:
//
//   - idt.rs       builds and loads the Interrupt Descriptor Table.
//   - handlers.rs  receives normalized frames from handlers.asm and dispatches
//                  exceptions / IRQs in Rust.
//   - apic.rs      owns interrupt-controller access: xAPIC, x2APIC, I/O APIC,
//                  PIC/PIT fallback, EOIs, IPIs and LAPIC timer setup.
//
// Design goals:
//   * BSP/AP split for SMP correctness.
//   * No `static mut` and no hidden global mutable references.
//   * IDT is built once, then loaded independently on every CPU.
//   * Local APIC setup is per-CPU; I/O APIC and PIC setup is BSP-owned.
//   * Existing public API remains available (`init`, `init_timer`, `enable`,
//     `disable`, `get_ticks`) while adding explicit SMP entry points.
//
// Boot sequencing:
//   BSP:
//       interrupts::disable();      // usually already disabled by early boot
//       interrupts::init();         // alias for init_bsp()
//       interrupts::init_timer(HZ);
//       interrupts::enable();
//
//   AP:
//       interrupts::disable();
//       interrupts::init_ap();      // load shared IDT, enable this CPU's LAPIC
//       interrupts::init_timer(HZ); // optional per-CPU LAPIC timer
//       interrupts::enable();
//
// Correctness notes:
//   * The BSP must call `init_bsp()` before APs call `init_ap()`.
//   * `idt::init()` builds the global table and loads it on the current CPU.
//     APs use `idt::load_current_cpu()` only.
//   * `apic::init()` performs global controller routing on the BSP.  APs use
//     `apic::init_local_current_cpu()` only.
//   * `USER_TRAP_INTERRUPT_VECTOR` is a software trap gate, not a hardware IRQ;
//     its Rust handler must not send EOI.  Hardware IRQ handlers do send EOI.

pub mod apic;
pub mod handlers;
pub mod idt;

use core::sync::atomic::{AtomicU8, Ordering};

use crate::{log_debug, log_info, log_warn};

// IRQ/vector assignments are generated by kernel/build.rs and are the single
// source of truth for Rust and assembly (`vectors.rs` / `vectors.inc`).
// Change vector numbers in build.rs, not here.
include!(concat!(env!("OUT_DIR"), "/vectors.rs"));

const LOG_ORIGIN: &str = "interrupts";

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
enum InitState {
    Cold = 0,
    BspInitializing = 1,
    BspReady = 2,
}

static INIT_STATE: AtomicU8 = AtomicU8::new(InitState::Cold as u8);

#[inline]
fn init_state() -> InitState {
    match INIT_STATE.load(Ordering::Acquire) {
        1 => InitState::BspInitializing,
        2 => InitState::BspReady,
        _ => InitState::Cold,
    }
}

#[inline]
fn set_init_state(state: InitState) {
    INIT_STATE.store(state as u8, Ordering::Release);
}

/// Initialize the interrupt subsystem on the bootstrap processor.
///
/// This is the compatibility entry point expected by the rest of the kernel.
/// It is deliberately an alias for `init_bsp()` so the BSP/AP split is explicit
/// for new SMP code while old call sites keep working.
pub fn init() {
    init_bsp();
}

/// Initialize the interrupt subsystem on the bootstrap processor (BSP).
///
/// The BSP owns global setup:
///   1. build and load the IDT;
///   2. initialize the interrupt controller fabric;
///   3. route external IRQs and neutralize the legacy PIC when APIC is active.
///
/// This function is idempotent after successful initialization.  A concurrent
/// second BSP initialization attempt is ignored rather than racing the IDT/APIC
/// setup path.
pub fn init_bsp() {
    match INIT_STATE.compare_exchange(
        InitState::Cold as u8,
        InitState::BspInitializing as u8,
        Ordering::AcqRel,
        Ordering::Acquire,
    ) {
        Ok(_) => {}
        Err(state) if state == InitState::BspReady as u8 => {
            log_debug!(LOG_ORIGIN, "BSP interrupt subsystem already initialized");
            return;
        }
        Err(_) => {
            log_warn!(
                LOG_ORIGIN,
                "BSP interrupt initialization is already in progress; ignoring duplicate call"
            );
            return;
        }
    }

    log_info!(LOG_ORIGIN, "Initializing interrupt subsystem on BSP...");

    // Exceptions must be safe before controller IRQs are routed or IF is set.
    idt::init();

    // Controller setup can now program LAPIC/x2APIC, I/O APIC, or PIC fallback.
    apic::init();

    set_init_state(InitState::BspReady);

    log_info!(
        LOG_ORIGIN,
        "Interrupt subsystem ready on BSP (local_apic_id={})",
        apic::local_apic_id()
    );
}

/// Initialize interrupt handling on the current application processor (AP).
///
/// APs do not rebuild global structures.  They load the IDTR with the shared
/// IDT and then enable/configure their own Local APIC instance.  This matches
/// the x86 SMP model: the IDT is memory-global, but the LAPIC is per-CPU even
/// when accessed through the same architectural xAPIC MMIO address.
pub fn init_ap() {
    if init_state() != InitState::BspReady {
        log_warn!(
            LOG_ORIGIN,
            "init_ap() called before BSP interrupt initialization completed"
        );
    }

    log_info!(LOG_ORIGIN, "Initializing interrupt subsystem on AP...");

    idt::load_current_cpu();
    apic::init_local_current_cpu();

    log_info!(
        LOG_ORIGIN,
        "Interrupt subsystem ready on AP (local_apic_id={})",
        apic::local_apic_id()
    );
}

/// Alias for AP bring-up code that wants a role-neutral name.
#[inline]
pub fn init_current_cpu() {
    init_ap();
}

/// Load the already-built IDT on the current CPU.
///
/// Useful during very early AP bring-up if the caller wants to split IDT load
/// from LAPIC enablement.  Normal AP startup should call `init_ap()` instead.
#[inline]
pub fn load_idt_current_cpu() {
    idt::load_current_cpu();
}

/// Configure the timer interrupt source for the current CPU.
///
/// In APIC mode this programs the Local APIC timer, so APs may call it too if
/// the scheduler wants per-CPU ticks.  In PIC fallback mode it configures the
/// single legacy PIT source.
#[inline]
pub fn init_timer(frequency_hz: u32) {
    apic::init_timer(frequency_hz);
}

/// More explicit alias for SMP code configuring per-CPU LAPIC timers.
#[inline]
pub fn init_timer_current_cpu(frequency_hz: u32) {
    init_timer(frequency_hz);
}

/// Globally enable maskable interrupts on the current CPU (`sti`).
#[inline]
pub fn enable() {
    apic::enable_interrupts();
}

/// Globally disable maskable interrupts on the current CPU (`cli`).
#[inline]
pub fn disable() {
    apic::disable_interrupts();
}

/// Return whether IF is set in the current CPU's RFLAGS.
#[inline]
pub fn interrupts_enabled() -> bool {
    let rflags: u64;
    unsafe {
        core::arch::asm!(
            "pushfq",
            "pop {}",
            out(reg) rflags,
            options(nomem, preserves_flags),
        );
    }
    (rflags & (1 << 9)) != 0
}

/// Run a closure with maskable interrupts disabled on the current CPU.
///
/// The previous IF state is restored on return.  This helper is intentionally
/// local-CPU only; it is not a substitute for locks protecting shared SMP data.
pub fn without_interrupts<R>(f: impl FnOnce() -> R) -> R {
    let was_enabled = interrupts_enabled();
    disable();
    let result = f();
    if was_enabled {
        enable();
    }
    result
}

/// Global timer tick count maintained by `handlers.rs`.
#[inline]
pub fn get_ticks() -> u64 {
    handlers::get_ticks()
}

/// Snapshot of interrupt counters maintained by `handlers.rs`.
#[inline]
pub fn irq_snapshot() -> handlers::IrqSnapshot {
    handlers::irq_snapshot()
}

/// Read this CPU's Local APIC ID, or 0 when running in legacy PIC mode.
#[inline]
pub fn local_apic_id() -> u32 {
    apic::local_apic_id()
}

/// Send an INIT IPI to a target Local APIC ID.
#[inline]
pub fn send_init_ipi(apic_id: u32) {
    apic::send_init_ipi(apic_id);
}

/// Send a STARTUP IPI to a target Local APIC ID.
#[inline]
pub fn send_startup_ipi(apic_id: u32, vector: u8) {
    apic::send_startup_ipi(apic_id, vector);
}

/// Request that another CPU enter the scheduler/reschedule path.
#[inline]
pub fn send_reschedule_ipi(apic_id: u32) {
    apic::send_reschedule_ipi(apic_id);
}

/// Current LAPIC timer down-counter, or 0 when no LAPIC timer exists.
#[inline]
pub fn timer_current_count() -> u32 {
    apic::timer_current_count()
}

/// Dump interrupt-controller state useful for low-level debugging.
#[inline]
pub fn debug_dump_state() {
    apic::dump_apic_state();
}

/// Halt forever with interrupts disabled.
///
/// This is intentionally tiny and architecture-local: fatal exception paths in
/// `handlers.rs` can call `crate::arch::halt()` directly, but orchestration code
/// occasionally needs a last-resort stop that also guarantees IF=0.
pub fn halt_disabled_forever() -> ! {
    disable();
    loop {
        crate::arch::halt();
    }
}

// Compile-time vector invariants duplicated here because this module is the
// public boundary for the interrupt subsystem.  `idt.rs` and build.rs also
// enforce the same rule.
const _: () = {
    assert!(TIMER_INTERRUPT_VECTOR >= 0x20);
    assert!(KEYBOARD_INTERRUPT_VECTOR >= 0x20);
    assert!(MOUSE_INTERRUPT_VECTOR >= 0x20);
    assert!(RESCHEDULE_INTERRUPT_VECTOR >= 0x20);
    assert!(USER_TRAP_INTERRUPT_VECTOR >= 0x20);
};
